### ISSUE TITLE
Not working on HBO Max on iOS 14

### ISSUE THREAD

**Issue by machineonamission** [opa334/NotRecording#1]
https://user-images.githubusercontent.com/35177464/157174757-63f8621d-f761-4b13-ad55-25f8dd1e5104.MOV

sorry for the bad quality, GitHub has an upload limit

iOS 14.2
iPad Pro (11-inch) (2nd generation)
Taurine 1.1.1
NotRecording 1.0

**Comment by machineonamission** [comment]
Sorry for the initial post with no content, I accidentally hit enter

**Comment by machineonamission** [comment]
The same behavior seems to be present on all apps if the tweak is enabled or not. no visible difference until you open the recording, the visuals have frozen but the audio is there until you exit. Definitely not how it used to work, perhaps there’s some new detection going on?

**Comment by opa334** [comment]
NotRecording is not a DRM bypass, it will not work for recording streaming services, it only prevents apps from accessing the screen recording state (which these apps do not do, they use a kernel level DRM called FairPlay).

**Comment by machineonamission** [comment]
Ah I see. Do you know of any bypasses to that? I just want to record small clips of a show I'm not interested in distributing the whole thing or anything

**Comment by opa334** [comment]
no

**Comment by machineonamission** [comment]
![image](https://user-images.githubusercontent.com/35177464/157286951-cd9dc989-fa61-4377-be8f-c76eb84d594a.jpeg)
